# Veja https://pre-commit.com para mais informações
repos:
  # Hooks básicos para a qualidade geral dos arquivos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # Remove espaços em branco no final das linhas
      - id: end-of-file-fixer  # Garante que os arquivos terminem com uma nova linha

  # Hooks específicos para Terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0 # Usando uma versão recente e estável
    hooks:
      - id: terraform_fmt
        description: Formata todo o código Terraform (.tf) para um padrão consistente.

      - id: terraform_validate
        description: Valida a sintaxe do código Terraform para evitar erros básicos.

      - id: terraform_docs
        description: Gera e atualiza a documentação de variáveis e saídas nos arquivos README.md.
        args:
          - --hook-config=--path-to-file=README.md        # Define o nome do arquivo de documentação
          - --hook-config=--create-file-if-not-exist=true # Cria o README.md se ele não existir
          - --args=--sort-by=required                     # Ordena as variáveis, colocando as obrigatórias primeiro
